### ISSUE TITLE
JSON-LD archive contents should contain @context specification

### ISSUE THREAD

**Issue by bkuczenski** [USEPA/USEEIO#13]
JSON-LD spec requires objects to include `@context` with something resembling the following contents: 
`"@context":"http://greendelta.github.io/olca-schema/context.jsonld"`

https://json-ld.org/
https://github.com/GreenDelta/olca-schema/blob/1ab2f1a52b8a85ab2c81e9fcaaebcbb4db38df20/examples/unit.json

**Comment by bl-young** [comment]
have you seen documentation anywhere for what that field is for?

**Comment by WesIngwersen** [comment]
They are intended to include a URL or multiple URLs where the terms in the spec are defined. The link used for the olca-schema isn't working. I will post an issue in olca-schema for it.

**Comment by bkuczenski** [comment]
It specifies how the entries in the JSON file are to be interpreted, i.e. what the dictionary entries "mean". Essentially, provides a semantic namespace for the keys. Without it, it's just JSON (i.e. not JSON-LD). With it, a reader will know how to interpret the fields. Since the OLCA schema does provide a context, schema-compliant files should use it

**Comment by WesIngwersen** [comment]
posted an issue here
https://github.com/GreenDelta/olca-schema/issues/6

**Comment by WesIngwersen** [comment]
@bkuczenski  I agree that is should be a part of any JSON-LD file but just noting that what the olca schema has created to be that context information is broken on multiple levels.

**Comment by WesIngwersen** [comment]
I think what would work for now would just be to use

`"@context":"http://greendelta.github.io/olca-schema/"`

**Comment by bl-young** [comment]
I can plan to add that field to all objects

**Comment by msrocka** [comment]
fyi: `@context` is not a required field and openLCA 2 will not write it anymore. It is only required when you want to fully expand the linked data graph with URIs etc. (e.g. define that enumeration values are not just strings but belong to the vocabulary) but then there are other ways to link the context for that.
