### ISSUE TITLE
Is is currency_converter correct? Can we find a better alternative for that package??

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#16]
https://github.com/USEPA/USEEIO/blob/344afe14d2b694116b0a98933ffd32ed0bfb7d41/import_factors_exio/useeio_imports_script.py#L5

I tried to install this from PyPi using pip 

>pip install currency_converter

It installed the package currency.converter 

Upon importing it for the first time i got an error because it depended on zope

I installed zope via pip but it is a whole application server and had a ton of dependencies. 

I modified the import line to read 
>from currency.converter import CurrencyConverter
but the latter is not an object of the former so that didn't work.

Rather than fix this, can we find another package that doesn't have so many dependencies and has been update

FYI @bl-young

**Comment by bl-young** [comment]
Hmm I dont recall have any issues at all when I first found and installed.

https://pypi.org/project/CurrencyConverter/

Looks like it should be:
> pip install currencyconverter

But i'm open to exploring other options.

**Comment by WesIngwersen** [comment]
OK it was just by change then that another package existed by that name in the code import statement

**Comment by WesIngwersen** [comment]
We just need to document some of those dependencies better if they are not already a dependency in TIEM

**Comment by bl-young** [comment]
> We just need to document some of those dependencies better if they are not already a dependency in TIEM

Yes - will add those to the readme you requested
