### ISSUE TITLE
Filtering of trade data with elementary flows?

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#19]
https://github.com/USEPA/USEEIO/blob/c4eb1700cdaf1345a584a81dbf94e74f2e3f8681/import_factors_exio/useeio_imports_script.py#L331

I don't think this is needed here

**Comment by bl-young** [comment]
Looks like the description here doesn't match the title @WesIngwersen

**Comment by bl-young** [comment]
we still do use the config file to get the field names, but the flows are not necessary
