### ISSUE TITLE
Clarify requirements for BEA and Census API keys and format

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#21]
https://github.com/USEPA/USEEIO/blob/c4eb1700cdaf1345a584a81dbf94e74f2e3f8681/import_factors_exio/API_Imports_Data_Script.py#L236C11-L236C11

```
FileNotFoundError: API key required for BEA_API. Create the file "../import_factors_exio/API/BEA_API_key.yaml" and add your API key
```

what is an example format for this yaml file containing the key?  
This requirement for a key and the format of this file is not documented

**Comment by Jnamovich** [comment]
Added guidance to readme
