### ISSUE TITLE
Key parameters should be at topic of file or require run with params passed separately

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#22]
https://github.com/USEPA/USEEIO/blob/c4eb1700cdaf1345a584a81dbf94e74f2e3f8681/import_factors_exio/useeio_imports_script.py#L494C49-L494C49

This script is designed to generate import factors 
1. over a span of year(s)
2. at a specified BEA level of detail

for 1, these parameter should either be clearly the the top of the file with the other params like the paths and not in this statement, or they should be required as params to be passed to this script upon execution

for 2, it's not that clear yet that this script only works at the Summary level which it appears to do. This needs to be very clear in the notes that it only works for that level.

**Comment by bl-young** [comment]
and also document what each of the output files is
