### ISSUE TITLE
Missing imports factors for {'481', '512', '211', '562'} where imports are present

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#25]
https://github.com/USEPA/USEEIO/blob/c4eb1700cdaf1345a584a81dbf94e74f2e3f8681/import_factors_exio/useeio_imports_script.py#L148

occurs with 2012 data.

**Comment by bl-young** [comment]
- 481 resolved due to incorrect exiobase -> BEA mapping
- 562 due to incompatible mapping; imports data maps to 562 while exiobase data map to the disaggregated waste sectors
- 211 is only missing in some years, seems to be a NAICS year issue because those naics got updated in 2017:

![image](https://github.com/USEPA/USEEIO/assets/44471635/99511d07-e9a8-4543-9e7c-7694c6bf97a4)

**Comment by bl-young** [comment]
@Jnamovich where did the census NAICS -> BEA mapping come from? it's missing some NAICS that only exist in 2012 but no longer exist in 2017

**Comment by bl-young** [comment]
512 fixed by 3ef6db0

**Comment by WesIngwersen** [comment]
Probably the 2 mapping files (that were updated in this commit )
https://github.com/USEPA/USEEIO/commit/a255b96f30dd130fc724783a3c3c7735874a59d5

 should be to -> useeio2 mappings to make it clear that the target list is not BEA detail but the USEEIO2 model schema.

**Comment by WesIngwersen** [comment]
> @Jnamovich where did the census NAICS -> BEA mapping come from? it's missing some NAICS that only exist in 2012 but no longer exist in 2017

Good catch.  Looks like those data were using 2012 NAICS until 2019 when they switched to 2017 NAICS.  Its that switch is not described in the data its something we should report to the API maintainers and maintain a config file mapping the source by data year to the right NAICS year and make sure our crosswalk has both like we have here in [flowsa under NAICS timeseries](https://github.com/USEPA/flowsa/blob/master/flowsa/data/NAICS_Crosswalk_TimeSeries.csv)
