### ISSUE TITLE
Make import shares independent of MRIO

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#53]
Per the original method in the [report](https://cfpub.epa.gov/si/si_public_record_report.cfm?dirEntryId=362470), the import shares should be independent of the MRIO model. 

Eq 1. 
$\Theta = \hat{m}^{-1} \Gamma$ 

text describing eq 1: 
_We use the import vector from the USEEIO model Use table which provides a total import value for each commodity.
We represent this here as $m$. We create an expanded version of the commodity import vector as $\Gamma$, whereby a unique column for every nation is given, so each value represents an import quantity per nation for a given year.  
The multiplication of the diagonalized inverse of the total import vector by the import by national matrix result is used to calculate the import share matrix, $\Theta$. $\Theta$ is commodity by nation import share matrix._

**Comment by bl-young** [comment]
The need for separate import shares file is due to, IIRC, the regional mapping, which is included in the file. I think we can probably not assign regions until after this file is created, but will need to look closer.

**Comment by WesIngwersen** [comment]
The best practice i think would be to have a separate script that outputs the Import Shares  and stores them in the repo..then reconfigure the [generate_import_factors.py](https://github.com/USEPA/USEEIO/blob/ceda/import_emission_factors/generate_import_factors.py)  to either read in (if they exist) or rerun that script.  If we think its pertinent we could instead use the more advanced Data Commons and esupy functionality for performing these checks like we used in flowsa and other TIEM tools
